// Instructions to turn on segments for special digit
export const dimmedSegments = {
    s1: false,
    s2: false,
    s3: false,
    s4: false,
    s5: false,
    s6: false,
    s7: false,
};

export const segmentsForDigit = {
    digit_0: {
        s1: true,
        s2: true,
        s3: true,
        s4: false,
        s5: true,
        s6: true,
        s7: true,
    },
    digit_1: {
        s1: false,
        s2: false,
        s3: false,
        s4: false,
        s5: false,
        s6: true,
        s7: true,
    },
    digit_2: {
        s1: false,
        s2: true,
        s3: true,
        s4: true,
        s5: true,
        s6: true,
        s7: false,
    },
    digit_3: {
        s1: false,
        s2: false,
        s3: true,
        s4: true,
        s5: true,
        s6: true,
        s7: true,
    },
    digit_4: {
        s1: true,
        s2: false,
        s3: false,
        s4: true,
        s5: false,
        s6: true,
        s7: true,
    },
    digit_5: {
        s1: true,
        s2: false,
        s3: true,
        s4: true,
        s5: true,
        s6: false,
        s7: true,
    },
    digit_6: {
        s1: true,
        s2: true,
        s3: true,
        s4: true,
        s5: true,
        s6: false,
        s7: true,
    },
    digit_7: {
        s1: false,
        s2: false,
        s3: true,
        s4: false,
        s5: false,
        s6: true,
        s7: true,
    },
    digit_8: {
        s1: true,
        s2: true,
        s3: true,
        s4: true,
        s5: true,
        s6: true,
        s7: true,
    },
    digit_9: {
        s1: true,
        s2: false,
        s3: true,
        s4: true,
        s5: true,
        s6: true,
        s7: true,
    }
};